echo "We are trying this practical from linux EC2"
echo "We are from batch-24 and learning git/gihub"
echo "Happy weekend"
echo "hello"
echo "gm"
echo "husband: i don't want to travel"
echo "wife: i want to travel"